#ifndef REQUESTSRESPONSES_H
#define REQUESTSRESPONSES_H

#define RESP_OK "OK"
#define RESP_FAILED "FAILED"

#define REQ_LOGIN "LOGIN"
#define REQ_MESSAGE "MESSAGE"
#define REQ_GET_PLAYERS "GET_PLAYERS"

#endif // REQUESTSRESPONSES_H
